name: No Response

# Both `issue_comment` and `schedule` event types are required for this Action
# to work properly.
# Details here: https://github.com/lee-dohm/no-response/blob/main/action.yml
on:
  workflow_dispatch: # disabled: lee-dohm/no-response is blocked by enterprise policy

jobs:
  noResponse:
    runs-on: ubuntu-latest
    steps:
      - uses: lee-dohm/no-response@v0.5.0
        with:
          token: ${{ github.token }}
          daysUntilClose: 30
          responseRequiredLabel: question
